app            = 'APPNAME'
primary_region = 'REGION'
kill_signal    = 'SIGINT'
kill_timeout   = '5s'

[experimental]
  auto_rollback = true

[build]

[env]
  TINI_SUBREAPER = 'true'

[[mounts]]
  source      = 'ftp_data'
  destination = '/data'

[http_service]
  internal_port        = 21
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ['app']

[[services]]
  protocol      = 'tcp'
  internal_port = 21
  [[services.ports]]
    port = 21

[[services]]
  protocol      = 'tcp'
  internal_port = 21000
  [[services.ports]]
    port = 21000

[[services]]
  protocol      = 'tcp'
  internal_port = 21001
  [[services.ports]]
    port = 21001

[[services]]
  protocol      = 'tcp'
  internal_port = 21002
  [[services.ports]]
    port = 21002

[[services]]
  protocol      = 'tcp'
  internal_port = 21003
  [[services.ports]]
    port = 21003

[[services]]
  protocol      = 'tcp'
  internal_port = 21004
  [[services.ports]]
    port = 21004

[[services]]
  protocol      = 'tcp'
  internal_port = 21005
  [[services.ports]]
    port = 21005

[checks]
  [checks.ftp]
    grace_period = "30s"
    interval     = "5s"
    port         = 21
    timeout      = "2s"
    type         = "tcp"

[services.concurrency]
  type       = "connections"
  hard_limit = 10
  soft_limit = 5

[[vm]]
  memory   = '1gb'
  cpu_kind = 'shared'
  cpus     = 1
